---
- hosts: localhost
  tasks:
  - name: Sending an email using Ansible
    mail:
      host: smtp.gmail.com
      port: 587
      username: tbajwa@gmail.com
      password: "$Dilber2022?"
      to: tbajwa86@hotmail.com
      subject: Testing Email By Ansible Yaml
      body: Sending email to test ansible yaml file
      secure: starttls
